name: Generate Snake Animation 🐍

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs automatically every 12 hours
  push:
    branches:
      - main
  workflow_dispatch:  # Optional manual trigger

jobs:
  build:
    name: Generate Snake 🐍
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push SVGs to output branch

    steps:
      - name: 🧩 Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Generate Snake Animations (Dark & Light)
        uses: Platane/snk@v3
        with:
          github_user_name: Dileep-git09
          outputs: |
            dist/snake-dark.svg?palette=github-dark
            dist/snake-light.svg?palette=github-light

      - name: 🚀 Push generated Snake animations
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
